#include <iostream.h>

void main()
{ int bil1, bil2;

cout<<"masukkan bilangan pertama = ";
cin>>bil1;
cout<<"masukkan bilangan kedua = ";
cin>>bil2;
cout<<"hasil "<<bil1<<" + "<<bil2<<" = "<<bil1+bil2;
cout<<"hasil "<<bil1<<" - "<<bil2<<" = "<<bil1-bil2;
cout<<"hasil "<<bil1<<" * "<<bil2<<" = "<<bil1*bil2;
cout<<"hasil "<<bil1<<" / "<<bil2<<" = "<<bil1/bil2;
cout<<"hasil "<<bil1<<" % "<<bil2<<" = "<<bil1%bil2;
return;
}

